before_install:
- sudo apt-get update && sudo apt-get install texlive-latex-base texlive-latex-recommended
  texlive-latex-extra texlive-fonts-extra texlive-fonts-recommended
script:
- pdflatex paper.tex
- bibtex paper
- pdflatex paper.tex
- pdflatex paper.tex
- if [ "$TRAVIS_BRANCH" == "master" ]; then bash ./deploy.sh; fi
env:
  global:
  - GH_REF: github.com/spring-studio-2016/article.git
  - secure: e2DdXiPmBjdSopFcncCH1gLwSSdeB70hYDq9l5lkKMjuwTjCgUIQxB/5peSkyR6vs00FSg/Z4d5M4bOth44sbjgA6cNAwIc623Jstb+VZ6xn6a2vlN1kOx9ii1unZUT64LWWAxjd17ncLROic2FtIg8ALX40fPUgW/sIGXNOw5KN1jzb1vv8/NJMqdVDbe/LrsAHOI1imdIo7OIVzu4iclXTRTIIAWN3egt5TcRhF1aQWm0cQpapb/gosKZgbacLMFMhtn8jTY/BbqBO05r3x2sr62YAykSoRHf1DtuhxGtgvhp8vI8IznOKh62W6aKVPdYax1/0wEVRH/hsDLkALybpIFlp3VeZHTd6p1jYKtFNctjPPI7CRYsE6IqMf4zF9jhgYu2By08V1OTGHybAxuWW9QQk751TMTst1VasHD/PbFQDrHLB18keKKDoybDigYGUF/jB9wxXQQMinKPA0Au6/oAe6MqBEQKqr7S6AJSlKVOa1esx0L4czLcqj6Vp32TpRYeD4YLeg7iLk6EeT6W7uHQmc7uNsuEQIqIYDRVznwlgilW5YCtYskff09GNwyD0NFPVwwgwYPB74IMwy8cT+KvsfHvEUmJfIT2wx0ubet68uPA65OiEi5lpHc1487ipcapbVBkDVn9DtybOPzDIMnLDgMfu3EXsBawlK2E=
notifications:
  slack:
    secure: dzr0KJomdn2IpmfGb2ZK3h5xeAeuCzJ1rqYx+VrHUzWhWlkPz6LQ4/UJc8+JhC52CfXUyQzLlLf/78McbQmjUb5AZrBxfyEzvACE+70XPH2irCn06zXud1GxjNvrY9Wx8GF3/P5VKRmIG7iJe8MbpooCg3IFaQ7m32BAqHGztpHU85NdFWg26f4F1YaWElQfmRjuKHp1xrqmlmNzDLug5RLC+AEnbB+M54BtmhTxrgzZ9BiwV0D/WiIimU3sUouiQR5RaSIYl8U00kScEgQINhiaCdZKphDClhfGo5pyOfhfqsRhLeP4PxUjC5LvuxULrcIoBHlCr51bVtbBSGI3H2M+svbZ8eJIHczqghBPIrUdAZI30AHC4uJeVseXK/s9o0eSfKV0D2/u4ROJhZRGB3gyeYX4zaAAihPRhzG77yIrBxFIXjEOByi5pC22LU1Hxyoe4XArBJg1LDNUtKUlspHw+idnlo9S5nR7zVI4rOCLe5pMvJbaoNz1slHyvrI7K6ILLfx7PqVAiceXWY8SC+e1NWnKfDf6QjIjJ79xaHn3mkWR1LXQQt6LJSPwuuEP2fwTd+ffFX/V00fqAGh/HtWw4Sbv3w6MjUHrIMdgZrgcGOCo/ubjftdiSD7VmGtz/c6FKQDTi3JaN4eQQF9dztm02zx9R4TRm4NNpbuL2t0=
